#!/usr/bin/env python3
"""swarm-build.py — LoveSpark Agent Swarm build orchestrator.

Standalone CLI that scaffolds, tracks, and audits swarm-driven builds
outside of Claude Code. The intelligence comes from Claude Code sessions;
this script handles project setup, wave tracking, and post-build audits.

Usage:
  python3 scripts/swarm-build.py new privacy link-cleaner "Strips tracking params"
  python3 scripts/swarm-build.py feature focus-blossom "Garden visualization"
  python3 scripts/swarm-build.py resume     # Resume from HANDOFF.md
  python3 scripts/swarm-build.py status     # Show wave completion status
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import date

BASE = "/Users/darkfire/Claude x LoveSpark"
SCRIPTS = f"{BASE}/scripts"
CATEGORIES = ["privacy", "neurodivergent", "reading", "themes", "productivity", "games", "full-power"]

CATEGORY_DIR = {
    "privacy": "privacy",
    "neurodivergent": "neurodivergent",
    "reading": "reading",
    "themes": "themes",
    "productivity": "productivity",
    "games": "Games",
    "full-power": "full-power",
}

WAVE_STATE_FILE = ".swarm-build-state.json"

SPECIALISTS = [
    "perf-profiler", "bundle-analyzer", "error-scanner", "privacy-guardian",
    "dead-code-hunter", "manifest-validator", "brand-auditor", "asset-validator",
    "pattern-miner", "docs-generator", "security-scanner", "dependency-auditor",
]

LEADS = ["carmack", "hamilton", "matz", "rauch", "karpathy", "linus"]


def today_str():
    return date.today().isoformat()


def get_ext_dir(category, name):
    cat_dir = CATEGORY_DIR.get(category, category)
    return f"{BASE}/Extensions/{cat_dir}/lovespark-{name}"


def get_existing_ext_dir(name):
    """Find an existing extension by name across all categories."""
    for cat_dir in CATEGORY_DIR.values():
        path = f"{BASE}/Extensions/{cat_dir}/lovespark-{name}"
        if os.path.isdir(path):
            return path
    # Try without lovespark- prefix
    for cat_dir in CATEGORY_DIR.values():
        cat_path = f"{BASE}/Extensions/{cat_dir}"
        if not os.path.isdir(cat_path):
            continue
        for entry in os.listdir(cat_path):
            if name in entry and os.path.isdir(os.path.join(cat_path, entry)):
                return os.path.join(cat_path, entry)
    return None


def load_state(work_dir):
    state_path = os.path.join(work_dir, WAVE_STATE_FILE)
    if os.path.exists(state_path):
        with open(state_path) as f:
            return json.load(f)
    return None


def save_state(work_dir, state):
    state_path = os.path.join(work_dir, WAVE_STATE_FILE)
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)
        f.write("\n")


def init_state(mode, name, category=None, description=""):
    return {
        "mode": mode,
        "name": name,
        "category": category,
        "description": description,
        "created": today_str(),
        "waves": {
            "wave1_research": "pending",
            "wave2_design": "pending",
            "wave3_gate": "pending",
            "wave4_build": "pending",
            "post_build": "pending",
        },
    }


def generate_research_template(mode, name, description, ext_dir=None):
    """Generate research.md template with sections for each specialist."""
    today = today_str()
    lines = [
        f"# Research — {name}",
        f"> Generated by swarm-build.py on {today}",
        f"> Mode: {mode}",
        f"> Description: {description}",
        "",
        "---",
        "",
    ]

    for specialist in SPECIALISTS:
        lines += [
            f"## {specialist}",
            "",
            f"<!-- {specialist}: Fill in your research findings here -->",
            "",
            "**Findings:**",
            "- (pending)",
            "",
            "**Recommendations:**",
            "- (pending)",
            "",
            "---",
            "",
        ]

    # Utility agent sections
    lines += [
        "## memory-agent",
        "",
        "**Known Issues Loaded:**",
        "- (pending)",
        "",
        "**Color Decisions Loaded:**",
        "- (pending)",
        "",
        "---",
        "",
        "## cross-sync",
        "",
        "**Naming Conflicts:** None found",
        "**Duplicate Functionality:** None found",
        "",
    ]

    if mode == "feature" and ext_dir:
        lines += [
            "---",
            "",
            "## Existing Extension Analysis",
            f"**Target:** `{ext_dir}`",
            "",
            "**Current Architecture:**",
            "- (pending — pattern-miner, error-scanner, brand-auditor analyze)",
            "",
        ]

    return "\n".join(lines) + "\n"


def generate_plan_template(mode, name, description):
    """Generate plan.md template with sections for each council lead."""
    today = today_str()
    lines = [
        f"# Plan — {name}",
        f"> Generated by swarm-build.py on {today}",
        f"> Mode: {mode}",
        f"> Description: {description}",
        "",
        "---",
        "",
    ]

    lead_sections = {
        "carmack": ("Architecture & Performance", [
            "Data flow diagram",
            "Storage schema",
            "Service worker lifecycle",
            "Performance budget",
        ]),
        "hamilton": ("Reliability & Error Handling", [
            "Error handling strategy",
            "Graceful degradation",
            "Edge cases",
            "Storage migration plan",
        ]),
        "matz": ("Code Structure & Quality", [
            "File structure",
            "Module boundaries",
            "Naming conventions",
            "API design",
        ]),
        "rauch": ("UI/UX & Brand", [
            "Popup layout",
            "Theme integration",
            "Accessibility plan",
            "Sparky placement",
            "Animation plan (with prefers-reduced-motion)",
        ]),
        "karpathy": ("Core Logic & Intelligence", [
            "Core algorithm",
            "Detection/blocking strategy",
            "Heuristics",
            "Configuration options",
        ]),
        "linus": ("Security & Privacy", [
            "CSP policy",
            "Permission justification",
            "Message handler validation",
            "Storage API consistency",
        ]),
    }

    for lead, (title, items) in lead_sections.items():
        emoji = {"carmack": "⚡", "hamilton": "🛡️", "matz": "🎨", "rauch": "✨", "karpathy": "🤖", "linus": "💀"}[lead]
        lines += [
            f"## {emoji} {lead.title()} — {title}",
            "",
            f"<!-- {lead}: Fill in your design here -->",
            "",
        ]
        for item in items:
            lines += [f"### {item}", "", "- (pending)", ""]
        lines += ["---", ""]

    # TODO checklist
    lines += [
        "## TODO Checklist",
        "",
        "<!-- Granular implementation checklist — each item should be one atomic task -->",
        "",
        "- [ ] (pending — leads populate after design rounds)",
        "",
    ]

    return "\n".join(lines) + "\n"


def generate_recon_report(name):
    """Generate BUILD-RECON report template."""
    today = today_str()
    lines = [
        f"# BUILD-RECON — {name}",
        f"> Date: {today}",
        f"> Status: Pending specialist reports",
        "",
        "---",
        "",
    ]

    for specialist in SPECIALISTS:
        lines += [f"## {specialist}", "", "Status: pending", "", "---", ""]

    lines += [
        "## Summary",
        "",
        "- **Blockers:** (none yet)",
        "- **Risks:** (none yet)",
        "- **Reusable assets found:** (pending)",
        "",
    ]

    return "\n".join(lines) + "\n"


def cmd_new(args):
    """Handle 'new' mode — scaffold a new extension."""
    category = args.category
    name = args.name
    description = args.description or f"LoveSpark {name.replace('-', ' ').title()}"
    ext_dir = get_ext_dir(category, name)

    if os.path.exists(ext_dir):
        print(f"Error: {ext_dir} already exists")
        sys.exit(1)

    print(f"🐝 Swarm Build — NEW extension")
    print(f"   Name: lovespark-{name}")
    print(f"   Category: {category}")
    print(f"   Description: {description}")
    print(f"   Directory: {ext_dir}")
    print()

    # Run scaffold-extension.py first (it creates the directory)
    scaffold_script = f"{SCRIPTS}/scaffold-extension.py"
    if os.path.exists(scaffold_script):
        print("   Running scaffold-extension.py...")
        result = subprocess.run(
            [sys.executable, scaffold_script,
             "--name", name,
             "--category", category,
             "--features", "stats,theme,toggle,content-script"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            print(result.stdout.strip())
        else:
            print(f"   Scaffold error: {result.stderr.strip()}")
            os.makedirs(ext_dir, exist_ok=True)
    else:
        print(f"   Warning: {scaffold_script} not found — creating directory manually")
        os.makedirs(ext_dir, exist_ok=True)

    print()

    # Create _reports directory
    os.makedirs(f"{ext_dir}/_reports", exist_ok=True)

    # Initialize wave state
    state = init_state("new", name, category, description)
    save_state(ext_dir, state)

    # Generate research.md template
    research = generate_research_template("new", name, description)
    with open(f"{ext_dir}/research.md", "w") as f:
        f.write(research)
    print(f"   Created: research.md")

    # Generate plan.md template
    plan = generate_plan_template("new", name, description)
    with open(f"{ext_dir}/plan.md", "w") as f:
        f.write(plan)
    print(f"   Created: plan.md")

    # Generate BUILD-RECON report
    recon = generate_recon_report(name)
    report_name = f"BUILD-RECON-{name}-{today_str()}.md"
    with open(f"{ext_dir}/_reports/{report_name}", "w") as f:
        f.write(recon)
    print(f"   Created: _reports/{report_name}")

    print()
    print("   Next steps:")
    print("   1. Open Claude Code in the extension directory")
    print(f"   2. Run: /swarm-build new {category} {name} \"{description}\"")
    print("   3. Swarm fills research.md (Wave 1) and plan.md (Wave 2-3)")
    print("   4. Review plan.md, add annotations")
    print("   5. Say 'implement it all' to trigger Wave 4")


def cmd_feature(args):
    """Handle 'feature' mode — add feature to existing extension."""
    ext_name = args.extension
    description = args.description or "New feature"
    ext_dir = get_existing_ext_dir(ext_name)

    if not ext_dir:
        print(f"Error: Could not find extension '{ext_name}' in any category")
        print("Available extensions:")
        for cat_dir in CATEGORY_DIR.values():
            cat_path = f"{BASE}/Extensions/{cat_dir}"
            if os.path.isdir(cat_path):
                for entry in sorted(os.listdir(cat_path)):
                    if os.path.isdir(os.path.join(cat_path, entry)):
                        print(f"  {cat_dir}/{entry}")
        sys.exit(1)

    print(f"🐝 Swarm Build — FEATURE")
    print(f"   Extension: {ext_dir}")
    print(f"   Feature: {description}")
    print()

    # Create _reports if needed
    os.makedirs(f"{ext_dir}/_reports", exist_ok=True)

    # Initialize wave state
    state = init_state("feature", ext_name, description=description)
    save_state(ext_dir, state)

    # Generate research.md template
    research = generate_research_template("feature", ext_name, description, ext_dir)
    research_path = f"{ext_dir}/research.md"
    if os.path.exists(research_path):
        # Don't overwrite existing research — use a dated version
        research_path = f"{ext_dir}/research-{today_str()}.md"
    with open(research_path, "w") as f:
        f.write(research)
    print(f"   Created: {os.path.basename(research_path)}")

    # Generate plan.md template
    plan = generate_plan_template("feature", ext_name, description)
    plan_path = f"{ext_dir}/plan.md"
    if os.path.exists(plan_path):
        plan_path = f"{ext_dir}/plan-{today_str()}.md"
    with open(plan_path, "w") as f:
        f.write(plan)
    print(f"   Created: {os.path.basename(plan_path)}")

    # Generate BUILD-RECON report
    recon = generate_recon_report(ext_name)
    report_name = f"BUILD-RECON-{ext_name}-{today_str()}.md"
    with open(f"{ext_dir}/_reports/{report_name}", "w") as f:
        f.write(recon)
    print(f"   Created: _reports/{report_name}")

    print()
    print("   Next steps:")
    print("   1. Open Claude Code in the extension directory")
    print(f"   2. Run: /swarm-build feature {ext_name} \"{description}\"")
    print("   3. Swarm fills research.md (Wave 1) and plan.md (Wave 2-3)")
    print("   4. Review plan.md, add annotations")
    print("   5. Say 'implement it all' to trigger Wave 4")


def cmd_status(args):
    """Show wave completion status for current or specified build."""
    # Try current directory first, then search
    search_dirs = [os.getcwd()]

    # Search all extension dirs
    for cat_dir in CATEGORY_DIR.values():
        cat_path = f"{BASE}/Extensions/{cat_dir}"
        if os.path.isdir(cat_path):
            for entry in os.listdir(cat_path):
                search_dirs.append(os.path.join(cat_path, entry))

    found = False
    for d in search_dirs:
        state = load_state(d)
        if state:
            found = True
            wave_icons = {
                "pending": "⬜",
                "in_progress": "🔄",
                "complete": "✅",
                "blocked": "🚫",
            }
            print(f"🐝 Swarm Build Status — {state['name']}")
            print(f"   Mode: {state['mode']}")
            print(f"   Created: {state['created']}")
            if state.get("description"):
                print(f"   Description: {state['description']}")
            print()
            for wave, status in state["waves"].items():
                icon = wave_icons.get(status, "❓")
                label = wave.replace("_", " ").title().replace("Wave", "Wave ")
                print(f"   {icon} {label}: {status}")
            print()

    if not found:
        print("No active swarm builds found.")
        print("Start one with: python3 scripts/swarm-build.py new [category] [name] [desc]")


def cmd_resume(args):
    """Resume from HANDOFF.md."""
    # Search for HANDOFF.md
    search_dirs = [os.getcwd()]
    for cat_dir in CATEGORY_DIR.values():
        cat_path = f"{BASE}/Extensions/{cat_dir}"
        if os.path.isdir(cat_path):
            for entry in os.listdir(cat_path):
                full = os.path.join(cat_path, entry)
                if os.path.isdir(full):
                    search_dirs.append(full)

    for d in search_dirs:
        handoff = os.path.join(d, "HANDOFF.md")
        if os.path.exists(handoff):
            print(f"🐝 Found HANDOFF.md at: {handoff}")
            print()
            with open(handoff) as f:
                print(f.read())
            state = load_state(d)
            if state:
                print("---")
                print(f"Build: {state['name']} ({state['mode']} mode)")
                for wave, status in state["waves"].items():
                    if status == "in_progress":
                        print(f"Resume at: {wave}")
            return

    print("No HANDOFF.md found in any extension directory.")
    print("Nothing to resume.")


def cmd_audit(args):
    """Run post-build audits on an extension."""
    ext_name = args.extension
    ext_dir = get_existing_ext_dir(ext_name)

    if not ext_dir:
        print(f"Error: Could not find extension '{ext_name}'")
        sys.exit(1)

    print(f"🐝 Running post-build audits on: {ext_dir}")
    print()

    # Run audit-contrast.py
    contrast_script = f"{SCRIPTS}/audit-contrast.py"
    if os.path.exists(contrast_script):
        print("── audit-contrast.py ──")
        subprocess.run([sys.executable, contrast_script, "--verbose", "--history"],
                       cwd=ext_dir)
        print()

    # Run audit-permissions.sh
    perms_script = f"{SCRIPTS}/audit-permissions.sh"
    if os.path.exists(perms_script):
        print("── audit-permissions.sh ──")
        subprocess.run(["bash", perms_script], cwd=ext_dir)
        print()

    # Run build-zips.sh
    zips_script = f"{SCRIPTS}/build-zips.sh"
    if os.path.exists(zips_script):
        print("── build-zips.sh ──")
        subprocess.run(["bash", zips_script], cwd=ext_dir)
        print()

    # Update state
    state = load_state(ext_dir)
    if state:
        state["waves"]["post_build"] = "complete"
        save_state(ext_dir, state)
        print("Post-build audits complete. Wave state updated.")


def main():
    parser = argparse.ArgumentParser(
        description="LoveSpark Agent Swarm — Build Orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python3 scripts/swarm-build.py new privacy link-cleaner "Strips tracking params"
  python3 scripts/swarm-build.py feature focus-blossom "Garden visualization"
  python3 scripts/swarm-build.py status
  python3 scripts/swarm-build.py resume
  python3 scripts/swarm-build.py audit focus-blossom""",
    )

    sub = parser.add_subparsers(dest="command", help="Build command")

    # new
    p_new = sub.add_parser("new", help="Build a new extension from scratch")
    p_new.add_argument("category", choices=CATEGORIES, help="Extension category")
    p_new.add_argument("name", help="Extension name (kebab-case, without lovespark- prefix)")
    p_new.add_argument("description", nargs="?", default="", help="Short description")

    # feature
    p_feat = sub.add_parser("feature", help="Add a feature to an existing extension")
    p_feat.add_argument("extension", help="Target extension name")
    p_feat.add_argument("description", nargs="?", default="", help="Feature description")

    # status
    sub.add_parser("status", help="Show wave completion status")

    # resume
    sub.add_parser("resume", help="Resume from HANDOFF.md")

    # audit
    p_audit = sub.add_parser("audit", help="Run post-build audits")
    p_audit.add_argument("extension", help="Extension to audit")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "new": cmd_new,
        "feature": cmd_feature,
        "status": cmd_status,
        "resume": cmd_resume,
        "audit": cmd_audit,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
